import type { Inputs, VariantId } from './types'
export const defaults: Inputs = {
  salaryCz:100000, annualBonus:200000, salarySkEur:2000, spending:30000, fx:24.35,
  moveMonth:60, horizonYears:20, inflation:.025, portfolioReturn:.05, dpsReturn:0, propertyGrowth:.025, buildingGrowth:.02, rentGrowth:.02,
  swr:.035, reserveTarget:1000000, saleCost:.03, cash:926000, portfolio:1120000, dps:700000, dpsAvailable:false,
  pragueValue:7000000, pragueDebt:3120963, praguePayment:18748, pragueRate:.0489, pragueRent:23000, pragueCosts:7000,
  berounValue:12000000, berounDebt:5870199, berounPayment:32263, berounRate:.0439, berounRent:25000, berounCosts:10000,
  personalDebt:986211, personalPayment:13368, personalRate:.064, buildingPriceEur:400000, buildingShare:.5, buildingLtv:.6, v6PragueDebtTarget:1750000,
  familyApartmentValueEur:120000, sisterPayoutEur:60000, familyBuildingLtv:.8,
  buildingRentEur:1800, buildingCostRate:.2, buildingRate:.06, buildingYears:15, housePriceEur:300000, houseMonth:84,
  houseLoanShare:0, houseRate:.05, houseYears:20, interimCzRent:25000, interimCzServices:7000, skHousing:0,
  fireLean:30000, fireComfort:50000, fireTravel:70000, retirementMonth:180
}
export const variants: Record<VariantId,{title:string;short:string;tags:string[]}> = {
  1:{title:'Predám Beroun, Praha zostane bez dlhu',short:'Čistý výnos z predaja Berouna vyčistí hypotéku Prahy aj osobný úver; dnešné úspory zostanú nedotknuté.',tags:['nízky dlh','česká základňa']},
  2:{title:'Predám Beroun, oddlžím Prahu a kúpim 50 % budovy',short:'Praha zostane bez hypotéky a pribudne financovaný podiel na budove.',tags:['partnerka','pasívny príjem']},
  3:{title:'Ponechám Prahu aj Beroun a kúpim 50 % budovy',short:'Oba byty zostanú s hypotékami a pribudne financovaný podiel na budove.',tags:['rast','vysoký dlh']},
  4:{title:'Predám Beroun, ponechám dlh Prahy a kúpim dom',short:'Pražská hypotéka pokračuje; budova sa nekupuje a po presune pribudne vlastný dom.',tags:['bývanie','bez budovy']},
  5:{title:'Predám Prahu, oddlžím Beroun a kúpim 50 % budovy',short:'Beroun zostane bez hypotéky a pribudne financovaný podiel na budove.',tags:['Beroun','chýba financovanie']},
  6:{title:'Predám Beroun, znížim dlh Prahy a kúpim 50 % budovy',short:'Časť pražskej hypotéky zostane, aby ostalo viac peňazí na budovu a rezervu.',tags:['vyvážený','likvidita']},
  7:{title:'Predám Prahu aj Beroun a budovu kúpim bez úveru',short:'České byty sa predajú; podiel budovy sa zaplatí bez novej hypotéky.',tags:['likvidita','jednoduchosť']},
  8:{title:'Predám Beroun, vyplatím sestru a založím rodinný byt',short:'Rodinný byt sa použije ako dodatočná zábezpeka pre vyššie financovanie 50 % budovy.',tags:['rodinný byt','dodatočná zábezpeka']}
}
export const inputGroups = [
  {title:'Životná časová os', fields:[['moveMonth','Presun na Slovensko','mesiac'],['retirementMonth','Koniec práce','mesiac'],['horizonYears','Horizont','rokov'],['fx','Kurz EUR','CZK/EUR']]},
  {title:'Príjem a život', fields:[['salaryCz','Čistá mzda v ČR','CZK/mes.'],['annualBonus','Ročná odmena','CZK/rok'],['salarySkEur','Čistá mzda na SK','EUR/mes.'],['spending','Osobná spotreba','CZK/mes.']]},
  {title:'Makro a FIRE', fields:[['portfolioReturn','Výnos portfólia','% p.a.'],['dpsReturn','Výnos DPS','% p.a.'],['inflation','Inflácia','% p.a.'],['propertyGrowth','Rast cien bytov a domu','% p.a.'],['buildingGrowth','Rast hodnoty budovy','% p.a.'],['swr','SWR','%']]},
  {title:'Ciele a veľké nákupy', fields:[['reserveTarget','Cieľ rezervy','CZK'],['buildingPriceEur','Cena budovy','EUR'],['buildingLtv','LTV budovy','%'],['familyApartmentValueEur','Hodnota rodinného bytu','EUR'],['sisterPayoutEur','Vyplatenie sestry','EUR'],['familyBuildingLtv','LTV budovy vo V8','%'],['housePriceEur','Cena domu','EUR'],['houseMonth','Kúpa domu','mesiac']]}
] as const

type InputMeta={label:string;unit:string;description:string;source:'Údaj používateľa'|'Prevzaté z predchádzajúceho modelu'|'Pracovný predpoklad'|'Potrebné doplniť';percent?:boolean}
export const inputMeta:Record<keyof Inputs,InputMeta> = {
  salaryCz:{label:'Čistá mzda v ČR',unit:'CZK/mesiac',description:'Pravidelná čistá mesačná mzda počas práce v Česku; ročný bonus sa pripočíta samostatne.',source:'Údaj používateľa'},
  annualBonus:{label:'Ročná odmena',unit:'CZK/rok',description:'Čistá ročná odmena vyplatená v jednom modelovom mesiaci, nie každý mesiac.',source:'Pracovný predpoklad'},
  salarySkEur:{label:'Čistá mzda na Slovensku',unit:'EUR/mesiac',description:'Príjem od presunu na Slovensko do ukončenia práce; nesčítava sa s českou mzdou.',source:'Údaj používateľa'},
  spending:{label:'Osobná spotreba',unit:'CZK/mesiac',description:'Bežné životné výdavky mimo samostatne modelovaných nákladov nehnuteľností.',source:'Údaj používateľa'},
  fx:{label:'Kurz EUR',unit:'CZK za 1 EUR',description:'Modelový kurz na prepočet eurových príjmov, budovy a domu do CZK.',source:'Prevzaté z predchádzajúceho modelu'},
  moveMonth:{label:'Presun na Slovensko',unit:'mesiac od štartu',description:'Mesiac, keď sa vypne česká mzda, zapne slovenská mzda a zmení sa bývanie aj prenájom bytov.',source:'Pracovný predpoklad'},
  horizonYears:{label:'Horizont modelu',unit:'rokov',description:'Dĺžka mesačnej projekcie používaná v grafoch, tabuľkách a FIRE výpočtoch.',source:'Pracovný predpoklad'},
  inflation:{label:'Inflácia',unit:'% p.a.',description:'Ročný rast životných a prevádzkových výdavkov; používa sa aj na prepočet do dnešných cien.',source:'Pracovný predpoklad',percent:true},
  portfolioReturn:{label:'Výnos portfólia',unit:'% p.a.',description:'Očakávaný nominálny ročný výnos investícií po poplatkoch, pred osobnými daňami.',source:'Pracovný predpoklad',percent:true},
  dpsReturn:{label:'Výnos DPS',unit:'% p.a.',description:'Očakávané nominálne zhodnotenie zostávajúcej hodnoty DPS. Nula zachováva konzervatívny predpoklad bez rastu.',source:'Pracovný predpoklad',percent:true},
  propertyGrowth:{label:'Rast cien nehnuteľností',unit:'% p.a.',description:'Nominálny ročný rast hodnoty bytov a domu; nie je to hotovostný príjem.',source:'Pracovný predpoklad',percent:true},
  buildingGrowth:{label:'Rast hodnoty budovy',unit:'% p.a.',description:'Nominálny ročný rast hodnoty komerčnej budovy. Je oddelený od rastu bytov a domu.',source:'Pracovný predpoklad',percent:true},
  rentGrowth:{label:'Rast nájomného',unit:'% p.a.',description:'Ročná indexácia príjmov z prenájmu Prahy, Berouna a budovy.',source:'Pracovný predpoklad',percent:true},
  swr:{label:'Bezpečná miera výberu (SWR)',unit:'%',description:'Orientačné percento portfólia použiteľné ročne na FIRE; nejde o garantovaný výnos.',source:'Pracovný predpoklad',percent:true},
  reserveTarget:{label:'Cieľ hotovostnej rezervy',unit:'CZK',description:'Suma, ktorú model prednostne drží v hotovosti pred ďalším investovaním.',source:'Pracovný predpoklad'},
  saleCost:{label:'Náklady predaja bytov',unit:'% z ceny',description:'Provízia a ďalšie transakčné náklady odpočítané z predajnej ceny nehnuteľnosti.',source:'Pracovný predpoklad',percent:true},
  cash:{label:'Peňažné úspory',unit:'CZK',description:'Likvidné zostatky na sporiacich účtoch ČSOB a VÚB na začiatku modelu.',source:'Údaj používateľa'},
  portfolio:{label:'Investičné portfólio',unit:'CZK',description:'Patria, ČSOB fondy a Revolut; dostupné investície bez viazaného DPS.',source:'Údaj používateľa'},
  dps:{label:'DPS / viazaný kapitál',unit:'CZK',description:'Doplnkové dôchodkové sporenie alebo poistenie zahrnuté v imaní, predvolene nie v likvidite ani skorom FIRE.',source:'Údaj používateľa'},
  dpsAvailable:{label:'DPS dostupné na použitie',unit:'áno/nie',description:'Ak je zapnuté, model smie DPS použiť na transakcie. Je to optimistická citlivosť, kým nepoznáme podmienky výberu.',source:'Potrebné doplniť'},
  pragueValue:{label:'Trhová hodnota Prahy',unit:'CZK',description:'Modelová trhová cena bytu Praha 2+kk; používateľ ju označil ako maximum.',source:'Údaj používateľa'},
  pragueDebt:{label:'Zostatok hypotéky Praha',unit:'CZK',description:'Nesplatená istina pražskej hypotéky k 10. 10. 2026.',source:'Údaj používateľa'},
  praguePayment:{label:'Splátka hypotéky Praha',unit:'CZK/mesiac',description:'Celá mesačná splátka; úrok je náklad a istina znižuje dlh.',source:'Údaj používateľa'},
  pragueRate:{label:'Úrok hypotéky Praha',unit:'% p.a.',description:'Nominálna ročná sadzba platná po refixácii od októbra 2026.',source:'Údaj používateľa',percent:true},
  pragueRent:{label:'Hrubé nájomné Praha',unit:'CZK/mesiac',description:'Inkaso pri prenájme vrátane energií; pri vlastnom bývaní je nájom nulový.',source:'Údaj používateľa'},
  pragueCosts:{label:'Prevádzkové náklady Praha',unit:'CZK/mesiac',description:'Energie a prevádzka bytu. Pri hrubom nájomnom sa odpočítajú iba raz.',source:'Údaj používateľa'},
  berounValue:{label:'Trhová hodnota Berouna',unit:'CZK',description:'Modelová trhová cena bytu Beroun 3+kk.',source:'Údaj používateľa'},
  berounDebt:{label:'Zostatok hypotéky Beroun',unit:'CZK',description:'Aktuálne nesplatená istina hypotéky na Beroun.',source:'Údaj používateľa'},
  berounPayment:{label:'Splátka hypotéky Beroun',unit:'CZK/mesiac',description:'Celá mesačná splátka hypotéky Beroun; splatnosť a refixáciu treba potvrdiť.',source:'Údaj používateľa'},
  berounRate:{label:'Úrok hypotéky Beroun',unit:'% p.a.',description:'Sadzba prevzatá zo staršieho čítania podkladov, preto má nižšiu istotu.',source:'Prevzaté z predchádzajúceho modelu',percent:true},
  berounRent:{label:'Potenciálne nájomné Beroun',unit:'CZK/mesiac',description:'Odhad hrubého nájmu po prenajatí; nejde o potvrdené súčasné inkaso.',source:'Údaj používateľa'},
  berounCosts:{label:'Prevádzkové náklady Beroun',unit:'CZK/mesiac',description:'Odhad energií a prevádzky bytu pri bývaní alebo prenájme.',source:'Údaj používateľa'},
  personalDebt:{label:'Zostatok osobného úveru',unit:'CZK',description:'Nesplatená istina osobného úveru, ktorý sa vo variantoch plánuje splatiť.',source:'Údaj používateľa'},
  personalPayment:{label:'Splátka osobného úveru',unit:'CZK/mesiac',description:'Mesačná dlhová služba osobného úveru do jeho splatenia.',source:'Údaj používateľa'},
  personalRate:{label:'Úrok osobného úveru',unit:'% p.a.',description:'Nominálna ročná úroková sadzba osobného úveru.',source:'Údaj používateľa',percent:true},
  buildingPriceEur:{label:'Cena celej budovy',unit:'EUR',description:'Kúpna cena celej komerčnej budovy v Humennom pred vedľajšími nákladmi.',source:'Údaj používateľa'},
  buildingShare:{label:'Váš podiel na budove',unit:'% vlastníctva',description:'Ekonomický vlastnícky podiel používateľa; 50 % znamená polovicu hodnoty, príjmov, nákladov a CAPEX.',source:'Údaj používateľa',percent:true},
  buildingLtv:{label:'LTV úveru na budovu',unit:'%',description:'Podiel kúpnej ceny vášho podielu financovaný novým úverom; zvyšok musí pokryť vlastný kapitál.',source:'Pracovný predpoklad',percent:true},
  v6PragueDebtTarget:{label:'Cieľový zostatok hypotéky Praha vo V6',unit:'CZK',description:'Zostatok pražskej hypotéky, na ktorý ju V6 zníži. Ak je aktuálny dlh nižší, model ho nezvýši.',source:'Pracovný predpoklad'},
  familyApartmentValueEur:{label:'Hodnota rodinného bytu',unit:'EUR',description:'Pracovná trhová hodnota bytu, ktorý otec prevedie na vás a sestru. Vo V8 po vyplatení sestry vlastníte 100 % bytu; otec v ňom naďalej býva.',source:'Potrebné doplniť'},
  sisterPayoutEur:{label:'Vyplatenie sestry',unit:'EUR',description:'Jednorazová suma zaplatená sestre výlučne z existujúcej hotovosti a portfólia. Model na túto platbu nevytvára nový úver.',source:'Údaj používateľa'},
  familyBuildingLtv:{label:'LTV budovy vo V8',unit:'%',description:'Pracovný podiel ceny budovy financovaný úverom pri dodatočnom založení rodinného bytu. Banka ho musí potvrdiť; nejde o ponuku.',source:'Pracovný predpoklad',percent:true},
  buildingRentEur:{label:'Externé nájomné budovy',unit:'EUR/mesiac',description:'Agregované externé nájomné celej budovy bez interného nájmu fitness.',source:'Pracovný predpoklad'},
  buildingCostRate:{label:'Prevádzková rezerva budovy',unit:'% z nájmu',description:'Zjednodušený odpočet na prevádzku, neobsadenosť a menšie opravy; v detailnom režime sa nesmie odpočítať druhýkrát.',source:'Prevzaté z predchádzajúceho modelu',percent:true},
  buildingRate:{label:'Úrok úveru na budovu',unit:'% p.a.',description:'Modelová sadzba nového úveru; nejde o bankovú ponuku.',source:'Pracovný predpoklad',percent:true},
  buildingYears:{label:'Splatnosť úveru na budovu',unit:'rokov',description:'Počet rokov použitý na výpočet anuitnej splátky úveru na budovu.',source:'Pracovný predpoklad'},
  housePriceEur:{label:'Cena domu v Humennom',unit:'EUR',description:'Pracovná cena vlastného bývania; menu a cenu treba potvrdiť.',source:'Potrebné doplniť'},
  houseMonth:{label:'Mesiac kúpy domu',unit:'mesiac od štartu',description:'Plánovaný okamih kúpy domu; pred týmto mesiacom dom nie je vaším aktívom.',source:'Pracovný predpoklad'},
  houseLoanShare:{label:'Podiel ceny domu financovaný úverom',unit:'%',description:'Časť kúpnej ceny domu hradená hypotékou. 0 % znamená celú kúpu za hotovosť, 50 % polovicu ceny na úver.',source:'Pracovný predpoklad',percent:true},
  houseRate:{label:'Úrok úveru na dom',unit:'% p.a.',description:'Modelová nominálna sadzba hypotéky na dom.',source:'Pracovný predpoklad',percent:true},
  houseYears:{label:'Splatnosť úveru na dom',unit:'rokov',description:'Počet rokov splácania hypotéky na dom.',source:'Pracovný predpoklad'},
  interimCzRent:{label:'Nájom v ČR po predaji bytov',unit:'CZK/mesiac',description:'Náhradné bývanie v Česku, ak sa oba byty predajú ešte pred presunom.',source:'Pracovný predpoklad'},
  interimCzServices:{label:'Služby k nájmu v ČR',unit:'CZK/mesiac',description:'Energie a služby platené navyše k nájmu v Česku.',source:'Pracovný predpoklad'},
  skHousing:{label:'Prechodné bývanie na Slovensku',unit:'CZK/mesiac',description:'Príspevok rodičom alebo nájom po presune a pred kúpou domu; nula je iba pracovný predpoklad.',source:'Potrebné doplniť'},
  fireLean:{label:'Lean FIRE rozpočet',unit:'CZK/mesiac',description:'Úsporný cieľový mesačný rozpočet v dnešných cenách.',source:'Pracovný predpoklad'},
  fireComfort:{label:'Comfort FIRE rozpočet',unit:'CZK/mesiac',description:'Komfortný cieľový mesačný rozpočet v dnešných cenách.',source:'Pracovný predpoklad'},
  fireTravel:{label:'Travel FIRE rozpočet',unit:'CZK/mesiac',description:'Vyšší cieľový rozpočet zahŕňajúci intenzívnejšie cestovanie.',source:'Pracovný predpoklad'},
  retirementMonth:{label:'Úplné ukončenie práce',unit:'mesiac od štartu',description:'Mesiac, od ktorého sa vypne mzda aj bonus a model čerpá pasívny príjem a portfólio.',source:'Pracovný predpoklad'}
}
