import { describe,expect,it } from 'vitest'
import { defaults } from './data'
import { initialNetWorth, runVariant, saleNet } from './engine'
describe('kontrolné výpočty',()=>{
  it('sedí východisková bilancia',()=>expect(initialNetWorth(defaults)).toBe(11768627))
  it('sedí čistý predaj',()=>{expect(saleNet(defaults.berounValue,defaults.berounDebt,.03)).toBe(5769801);expect(saleNet(defaults.pragueValue,defaults.pragueDebt,.03)).toBe(3669037)})
  it('V1 a V7 rešpektujú disponibilitu DPS',()=>{const v1=runVariant(defaults,1);const v7=runVariant(defaults,7);expect(Math.round(v1.initialLiquid)).toBe(3708627);expect(Math.round(v7.initialLiquid)).toBe(5628627)})
  it('presun mení mzdu až v nasledujúcom mesiaci a bonus je iba raz ročne',()=>{const r=runVariant(defaults,1);expect(r.timeline[58].income).toBe(100000);expect(r.timeline[59].income).toBe(300000);expect(r.timeline[60].income).toBe(100000);expect(r.timeline[61].income).toBe(defaults.salarySkEur*defaults.fx)})
  it('Praha sa prenajíma až po presune',()=>{const r=runVariant(defaults,3);expect(r.timeline[12].passive).toBeGreaterThan(0);expect(r.timeline[61].passive).toBeGreaterThan(r.timeline[60].passive)})
  it('Comfort FIRE pokrytie je konečný pomer',()=>{const coverage=runVariant(defaults,6).fireCoverage;expect(Number.isFinite(coverage)).toBe(true);expect(coverage).toBeGreaterThanOrEqual(0)})
  it('V8 vyplatí sestru z vlastných zdrojov a rodinný byt pridá ako aktívum',()=>{const r=runVariant(defaults,8);expect(Math.round(r.initialLiquid)).toBe(1273627);expect(Math.round(r.initialDebt)).toBe(3896000);expect(Math.round(r.timeline[0].familyApartment)).toBe(2922000);expect(r.timeline[0].personalDebt).toBe(0);expect(r.timeline[0].pragueDebt).toBe(0)})
  it('V2 oddeľuje cenu podielu budovy, nový úver a vlastný vklad',()=>{const r=runVariant(defaults,2);const share=defaults.buildingPriceEur*defaults.fx*defaults.buildingShare;expect(share).toBe(4870000);expect(r.initialDebt).toBe(2922000);expect(share-r.initialDebt).toBe(1948000)})
  it('má úvodný stav a presne 240 mesačných období pri 20 rokoch',()=>{const r=runVariant(defaults,1);expect(r.timeline).toHaveLength(defaults.horizonYears*12+1);expect(r.timeline[0].income).toBe(0);expect(r.timeline.at(-1)?.month).toBe(240)})
  it('po presune rozpisuje osobnú spotrebu, bývanie, prevádzku budovy a splátky bez rozdielu',()=>{const r=runVariant(defaults,2),m=r.timeline[61],b=m.breakdown,growth=Math.pow(1+defaults.rentGrowth,61/12),buildingRent=defaults.buildingRentEur*defaults.fx*defaults.buildingShare*growth;expect(b.slovakiaHousing).toBe(defaults.skHousingEur*defaults.fx);expect(b.buildingOperating).toBeCloseTo(buildingRent*defaults.buildingCostRate,6);expect(b.buildingLoan).toBeGreaterThan(0);expect(m.expenses).toBeCloseTo(b.personalSpending+b.pragueOperating+b.berounOperating+b.buildingOperating+b.slovakiaHousing+b.czechHousing,6);expect(m.debtService).toBeCloseTo(b.pragueLoan+b.berounLoan+b.personalLoan+b.buildingLoan+b.houseLoan,6);expect(m.freeCash).toBeCloseTo(m.income+m.passive-m.expenses-m.debtService,6)})
  it('čiastočná splátka osobného úveru znižuje jeho zostatok',()=>{const r=runVariant({...defaults,cash:100,portfolio:0,dps:0,personalDebt:1000,buildingPriceEur:0},3);expect(r.timeline[0].personalDebt).toBe(900);expect(r.deficit).toBeGreaterThanOrEqual(900)})
  it('predaj pod vodou sa bez zdrojov nevykoná',()=>{const r=runVariant({...defaults,cash:0,portfolio:0,dps:0,personalDebt:0,pragueDebt:0,berounValue:100,berounDebt:1000,buildingPriceEur:0},1);expect(r.timeline[0].beroun).toBe(100);expect(r.timeline[0].berounDebt).toBe(1000);expect(r.feasible).toBe(false)})
  it('nedofinancovaná budova sa nekúpi a nevytvorí úver ani nájom',()=>{const r=runVariant({...defaults,cash:0,portfolio:0,dps:0,personalDebt:0,buildingPriceEur:400000},3);expect(r.timeline[0].building).toBe(0);expect(r.timeline[0].buildingDebt).toBe(0);expect(r.feasible).toBe(false)})
  it('V6 nezvýši nízku pražskú hypotéku na cieľ',()=>{const r=runVariant({...defaults,pragueDebt:1000000,v6PragueDebtTarget:1750000},6);expect(r.timeline[0].pragueDebt).toBeLessThanOrEqual(1000000)})
  it('sprístupnené DPS je zahrnuté vo FIRE portfóliu',()=>{const locked=runVariant({...defaults,buildingPriceEur:0},3),available=runVariant({...defaults,buildingPriceEur:0,dpsAvailable:true},3);expect(available.timeline[0].firePortfolio-locked.timeline[0].firePortfolio).toBe(defaults.dps)})
  it('nedostatočná splátka kapitalizuje nezaplatený úrok',()=>{const r=runVariant({...defaults,pragueDebt:1000000,praguePayment:1000,personalDebt:0,buildingPriceEur:0},3);expect(r.timeline[1].pragueDebt).toBeGreaterThan(r.timeline[0].pragueDebt)})
  it('stres príjmu budovy trvá iba 12 mesiacov po presune',()=>{const base=runVariant(defaults,2),stress=runVariant(defaults,2,.2);expect(stress.timeline[61].passive).toBeLessThan(base.timeline[61].passive);expect(stress.timeline[72].passive).toBeLessThan(base.timeline[72].passive);expect(stress.timeline[73].passive).toBeCloseTo(base.timeline[73].passive,6)})
})
